"""Open Assembly API client."""

# Code generated by OpenAssembly-Binder. DO NOT EDIT.
# https://github.com/kr-data-kit/KAssembly-CodeGen

from __future__ import annotations

from typing import Any, Mapping, Sequence, TypeVar
from urllib.parse import urlencode

import requests
from pydantic import BaseModel, TypeAdapter

from exceptions import APIError, ResponseParseError
from models import APIResponse, BaseParams, _ItemContainer, _Result
from status import APIStatus


__all__ = ["Client"]


BASE_URL = "https://open.assembly.go.kr/portal/openapi/"
BULK_JSON_URL = "https://open.assembly.go.kr/portal/data/sheet/downloadSheetData.do"

T = TypeVar("T", bound=BaseModel)


class Client:
    """Client for interacting with the Open Assembly API.
    
    Attributes:
        api_key: API authentication key
        session: Requests session for connection pooling
    """
    
    def __init__(self, api_key: str) -> None:
        """Initialize the client.
        
        Args:
            api_key: Open Assembly API key
        """
        self.api_key = api_key
        self.session = requests.Session()
    
    def __enter__(self) -> Client:
        """Context manager entry."""
        return self
    
    def __exit__(self, *args: Any) -> None:
        """Context manager exit."""
        self.close()
    
    def close(self) -> None:
        """Close the HTTP session."""
        self.session.close()

    def _common_headers(self) -> dict[str, str]:
        """Return common headers equivalent to Go setCommonHeaders."""
        return {
            "Content-Type": "application/json",
            "Host": "open.assembly.go.kr",
            "User-Agent": "Mozilla/5.0",
        }
    
    def _build_url(self, endpoint: str, params: BaseParams) -> str:
        """Build complete API URL with query parameters.
        
        Args:
            endpoint: API endpoint name
            params: Request parameters
            
        Returns:
            Complete URL with encoded query parameters
        """
        query_params = {"KEY": self.api_key}
        query_params.update(params.to_query_params())
        return f"{BASE_URL}{endpoint}?{urlencode(query_params)}"
    
    def _fetch_api(
        self,
        endpoint: str,
        params: BaseParams,
        response_model: type[T],
    ) -> APIResponse[T]:
        """Fetch data from API endpoint.
        
        Args:
            endpoint: API endpoint name
            params: Request parameters
            response_model: Pydantic model for response data
            
        Returns:
            Parsed API response
            
        Raises:
            APIError: If API returns an error
            ResponseParseError: If response cannot be parsed
            requests.RequestException: If HTTP request fails
        """
        url = self._build_url(endpoint, params)
        response = self.session.get(
            url,
            headers=self._common_headers(),
            timeout=30,
        )
        response.raise_for_status()
        
        data = response.json()
        
        # Check for error response
        if "RESULT" in data:
            result = _Result.model_validate(data["RESULT"])
            status = APIStatus.from_code(result.code)
            
            if status == APIStatus.NO_DATA:
                return APIResponse(status=status, data=[], source="api")
            
            raise APIError(result.code, result.message)
        
        # Extract endpoint data
        if endpoint not in data:
            raise ResponseParseError(
                f"Response missing expected key: '{endpoint}'"
            )
        
        # Parse response items
        try:
            adapter = TypeAdapter(list[_ItemContainer[response_model]])
            items = adapter.validate_python(data[endpoint])
        except Exception as e:
            raise ResponseParseError(f"Failed to parse response: {e}") from e
        
        if len(items) < 2:
            raise ResponseParseError("Insufficient data in response")
        
        # Second item contains actual data (first is metadata)
        actual_data = items[1].row or []
        
        return APIResponse(
            status=APIStatus.OK,
            data=actual_data,
            source="api",
        )
    
    def _fetch_bulk_json(
        self,
        inf_id: str,
        inf_seq: str,
        param_fields: Sequence[str],
        param_values: Mapping[str, str] | None,
        response_model: type[T],
    ) -> APIResponse[T]:
        """Fetch bulk JSON data.
        
        Args:
            inf_id: Information ID
            inf_seq: Information sequence
            param_fields: Parameter field mappings
            response_model: Pydantic model for response data
            
        Returns:
            Parsed API response
            
        Raises:
            ResponseParseError: If response cannot be parsed
            requests.RequestException: If HTTP request fails
        """
        form_data = {
            "infId": inf_id,
            "infSeq": inf_seq,
            "downloadType": "J",
        }
        
        # Go implementation behavior: include every declared endpoint parameter
        # even when its value is empty.
        form_pairs: list[tuple[str, str]] = [
            ("infId", form_data["infId"]),
            ("infSeq", form_data["infSeq"]),
            ("downloadType", form_data["downloadType"]),
        ]
        for field in param_fields:
            value = ""
            if param_values is not None:
                value = param_values.get(field, "")
            form_pairs.append((field, "" if value is None else str(value)))
        
        response = self.session.post(
            BULK_JSON_URL,
            data=form_pairs,
            headers={
                **self._common_headers(),
                "Content-Type": "application/x-www-form-urlencoded",
                "Accept-Encoding": "gzip",
            },
            timeout=60,
        )
        response.raise_for_status()
        
        try:
            data = response.json()
        except requests.exceptions.JSONDecodeError as e:
            # Check if response is HTML (error page)
            content_type = response.headers.get('content-type', '').lower()
            if 'html' in content_type:
                # Extract error message from HTML if available
                import re
                title_match = re.search(r'<title>(.+?)</title>', response.text)
                error_title = title_match.group(1) if title_match else 'Unknown'
                raise ResponseParseError(
                    f"Bulk endpoint returned HTML error page: '{error_title}'. "
                    f"This may indicate: invalid INF_ID, invalid INF_SEQ, "
                    f"authentication issue, or server-side business logic error."
                ) from e
            else:
                # Invalid JSON response
                raise ResponseParseError(
                    f"Bulk endpoint returned invalid JSON. "
                    f"Status: {response.status_code}, "
                    f"Content-Type: {content_type}. "
                    f"Response text (first 300 chars): {response.text[:300]}"
                ) from e
        
        if not isinstance(data, list) or len(data) < 2:
            return APIResponse(
                status=APIStatus.NO_DATA,
                data=[],
                source="bulk-json",
            )
        
        # First item is header, rest is data
        try:
            adapter = TypeAdapter(list[response_model])
            result_data = adapter.validate_python(data[1:])
        except Exception as e:
            raise ResponseParseError(f"Failed to parse bulk data: {e}") from e
        
        return APIResponse(
            status=APIStatus.OK,
            data=result_data,
            source="bulk-json",
        )
    
    def fetch(
        self,
        endpoint: str,
        params: BaseParams,
        response_model: type[T],
    ) -> APIResponse[T]:
        """Fetch data from API endpoint.
        
        This is a public wrapper around _fetch_api for user convenience.
        
        Args:
            endpoint: API endpoint name
            params: Request parameters
            response_model: Pydantic model for response data
            
        Returns:
            Parsed API response
            
        Raises:
            APIError: If API returns an error
            ResponseParseError: If response cannot be parsed
        """
        return self._fetch_api(endpoint, params, response_model)
    
    def fetch_bulk(
        self,
        inf_id: str,
        inf_seq: str,
        param_fields: Sequence[str],
        param_values: Mapping[str, str] | None,
        response_model: type[T],
    ) -> APIResponse[T]:
        """Fetch bulk JSON data.
        
        This is a public wrapper around _fetch_bulk_json for user convenience.
        
        Args:
            inf_id: Information ID
            inf_seq: Information sequence
            param_fields: Parameter field mappings
            response_model: Pydantic model for response data
            
        Returns:
            Parsed API response
            
        Raises:
            ResponseParseError: If response cannot be parsed
        """
        return self._fetch_bulk_json(
            inf_id,
            inf_seq,
            param_fields,
            param_values,
            response_model,
        )

