"""Custom exceptions for Open Assembly API client."""

# Code generated by OpenAssembly-Binder. DO NOT EDIT.
# https://github.com/kr-data-kit/KAssembly-CodeGen

from __future__ import annotations


class openassemblyclientError(Exception):
    """Base exception for Open Assembly API errors."""
    
    pass


class APIError(openassemblyclientError):
    """Exception raised when API returns an error response."""
    
    def __init__(self, code: str, message: str) -> None:
        self.code = code
        self.message = message
        super().__init__(f"{code}: {message}")


class InvalidParameterError(openassemblyclientError):
    """Exception raised when request parameters are invalid."""
    
    pass


class ResponseParseError(openassemblyclientError):
    """Exception raised when response cannot be parsed."""
    
    pass
