"""API endpoint modules.

Usage:
    from endpoints import <api endpoint module>
    
    # Example with specific endpoint
    params = allbill.Params(...)
    response = client.fetch(allbill.ENDPOINT, params, allbill.Response)
    # or use the convenience function
    response = allbill.fetch(client, params)
"""

# Code generated by OpenAssembly-Binder. DO NOT EDIT.
# https://github.com/kr-data-kit/KAssembly-CodeGen

# Endpoint modules are imported as namespaces
from . import (
    allbill,
    opensrvapi,
    vconfbudgetconflist,
)

__all__ = [
    "allbill",
    "opensrvapi",
    "vconfbudgetconflist",
]
