"""API endpoint modules.

Usage:
    from endpoints import <api endpoint module>
    
    # Example with specific endpoint
    params = opensrvapi.Params(...)
    response = client.fetch(opensrvapi.ENDPOINT, params, opensrvapi.Response)
    # or use the convenience function
    response = opensrvapi.fetch(client, params)
"""

# Code generated by OpenAssembly-Binder. DO NOT EDIT.
# https://github.com/kr-data-kit/KAssembly-CodeGen

# Endpoint modules are imported as namespaces
from . import (
    opensrvapi,
    vconfbudgetconflist,
)

__all__ = [
    "opensrvapi",
    "vconfbudgetconflist",
]
