"""ALLBILL endpoint 

ID : OOWY4R001216HX11440
의안정보 통합 API (Version 1)
의안정보 통합 API의 정보를 제공합니다. - Updated Version
URL : https://open.assembly.go.kr/portal/data/service/selectAPIServicePage.do/OOWY4R001216HX11440
CCL : 공공누리 - 공공저작물 자유이용허락 : 출처표시

"""

# Code generated by OpenAssembly-Binder. DO NOT EDIT.
# https://github.com/kr-data-kit/KAssembly-CodeGen

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

from models import APIResponse, BaseParams

if TYPE_CHECKING:
    from client import Client

__all__ = [
    "Params",
    "Response",
    "fetch",
    "fetch_bulk",
]

# Endpoint metadata
ENDPOINT = "ALLBILL"
INF_ID = "OOWY4R001216HX11440"
INF_SEQ = "1"


class Params(BaseParams):
    """Request parameters for ALLBILL endpoint.

    This endpoint provides 의안정보 통합 API (Version 1)

    Required fields:
        bill_no: 의안번호
    Optional fields:
        bill_id: 의안ID
        bill_knd: 의안종류
        bill_nm: 의안명
        ppsr_knd: 제안자구분
        ppsl_dt: 제안일
        jrcmit_nm: 소관위원회명
        rgs_conf_rslt: 본회의 심의결과
    """

    # Required
    bill_no: str = Field(..., description="의안번호")

    # Optional - only added to query if not empty
    bill_id: str | None = Field(default=None, description="의안ID")
    bill_knd: str | None = Field(default=None, description="의안종류")
    bill_nm: str | None = Field(default=None, description="의안명")
    ppsr_knd: str | None = Field(default=None, description="제안자구분")
    ppsl_dt: str | None = Field(default=None, description="제안일")
    jrcmit_nm: str | None = Field(default=None, description="소관위원회명")
    rgs_conf_rslt: str | None = Field(default=None, description="본회의 심의결과")

    model_config = ConfigDict(
        populate_by_name=True,
    )

    def to_query_params(self) -> dict[str, Any]:
        """Convert parameters to URL query parameters.
        
        Only non-empty values are included in the query parameters.
        """
        params = super().to_query_params()

        # Required parameter
        params["BILL_NO"] = self.bill_no

        # Optional parameters - only add if not None and not empty
        if self.bill_no :
            params["BILL_NO"] = self.bill_no

        return params

class Response(BaseModel):
    """Response model for ALLBILL endpoint."""
    eraco: str = Field(alias="ERACO", description="대수")
    bill_id: str = Field(alias="BILL_ID", description="의안ID")
    bill_no: str = Field(alias="BILL_NO", description="의안번호")
    bill_knd: str = Field(alias="BILL_KND", description="의안종류")
    bill_nm: str = Field(alias="BILL_NM", description="의안명")
    ppsr_knd: str = Field(alias="PPSR_KND", description="제안자구분")
    ppsr_nm: str = Field(alias="PPSR_NM", description="제안자명")
    ppsl_sess: str = Field(alias="PPSL_SESS", description="제안회기")
    ppsl_dt: str = Field(alias="PPSL_DT", description="제안일")
    jrcmit_nm: str = Field(alias="JRCMIT_NM", description="소관위원회명")
    jrcmit_cmmt_dt: str = Field(alias="JRCMIT_CMMT_DT", description="소관위원회 회부일")
    jrcmit_prsnt_dt: str = Field(alias="JRCMIT_PRSNT_DT", description="소관위원회 상정일")
    jrcmit_proc_dt: str = Field(alias="JRCMIT_PROC_DT", description="소관위원회 처리일")
    jrcmit_proc_rslt: str = Field(alias="JRCMIT_PROC_RSLT", description="소관위원회 처리결과")
    law_cmmt_dt: str = Field(alias="LAW_CMMT_DT", description="법사위 체계자구심사 회부일")
    law_prsnt_dt: str = Field(alias="LAW_PRSNT_DT", description="법사위 체계자구심사 상정일")
    law_proc_dt: str = Field(alias="LAW_PROC_DT", description="법사위 체계자구심사 처리일")
    law_proc_rslt: str = Field(alias="LAW_PROC_RSLT", description="법사위 체계자구심사 처리결과")
    rgs_prsnt_dt: str = Field(alias="RGS_PRSNT_DT", description="본회의 심의 상정일")
    rgs_rsln_dt: str = Field(alias="RGS_RSLN_DT", description="본회의 심의 의결일")
    rgs_conf_nm: str = Field(alias="RGS_CONF_NM", description="본회의 심의 회의명")
    rgs_conf_rslt: str = Field(alias="RGS_CONF_RSLT", description="본회의 심의결과")
    gvrn_trsf_dt: str = Field(alias="GVRN_TRSF_DT", description="정부 이송일")
    prom_law_nm: str = Field(alias="PROM_LAW_NM", description="공포 법률명")
    prom_dt: str = Field(alias="PROM_DT", description="공포일")
    prom_no: str = Field(alias="PROM_NO", description="공포번호")
    link_url: str = Field(alias="LINK_URL", description="링크URL")
    
    model_config = ConfigDict(
        populate_by_name=True,
        str_strip_whitespace=True,
    )

    @field_validator("*", mode="before")
    @classmethod
    def convert_to_string(cls, v: Any) -> str:
        """Convert all values to string.
        
        API may return numbers or other types instead of strings.
        """
        if v is None:
            return ""
        return str(v)

def fetch(
    client: Client,
    params: Params,
) -> APIResponse[Response]:
    """Fetch ALLBILL data from API.

    Args:
        client: API client instance
        params: Request parameters 

    Returns:
        API response with ALLBILL data
    """
    return client._fetch_api(
        endpoint=ENDPOINT,
        params=params,
        response_model=Response,
    )
def fetch_bulk(
    client: Client,
    params: Params | None = None,
) -> APIResponse[Response]:
    """Fetch all ALLBILL data via bulk JSON endpoint.

    Note: This method can handle large datasets (10,000+ items) but may
    impose significant load. Use sparingly for very large datasets.

    Args:
        client: API client instance
    
    Returns:
        API response with all ALLBILL data
    """
    param_fields = [
        "BILL_ID",
        "BILL_NO",
        "BILL_KND",
        "BILL_NM",
        "PPSR_KND",
        "PPSL_DT",
        "JRCMIT_NM",
        "RGS_CONF_RSLT",
    ]
    param_values = None
    if params is not None:
        param_values = {
            "BILL_ID": params.bill_id or "",
            "BILL_NO": params.bill_no or "",
            "BILL_KND": params.bill_knd or "",
            "BILL_NM": params.bill_nm or "",
            "PPSR_KND": params.ppsr_knd or "",
            "PPSL_DT": params.ppsl_dt or "",
            "JRCMIT_NM": params.jrcmit_nm or "",
            "RGS_CONF_RSLT": params.rgs_conf_rslt or "",
        }
    
    return client.fetch_bulk(
        inf_id=INF_ID,
        inf_seq=INF_SEQ,
        param_fields=param_fields,
        param_values=param_values,
        response_model=Response,
    )
