"""OPENSRVAPI endpoint 

ID : OOBAOA001213RL17443
OPEN API 전체 현황
OPEN API 전체현황
URL : https://open.assembly.go.kr/portal/data/service/selectAPIServicePage.do/OOBAOA001213RL17443
CCL : 공공누리 - 공공저작물 자유이용허락 : 출처표시

"""

# Code generated by OpenAssembly-Binder. DO NOT EDIT.
# https://github.com/kr-data-kit/KAssembly-CodeGen

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

from models import APIResponse, BaseParams

if TYPE_CHECKING:
    from client import Client

__all__ = [
    "Params",
    "Response",
    "fetch",
]

# Endpoint metadata
ENDPOINT = "OPENSRVAPI"
INF_ID = "OOBAOA001213RL17443"
INF_SEQ = ""


class Params(BaseParams):
    """Request parameters for OPENSRVAPI endpoint.

    This endpoint provides OPEN API 전체 현황

    Required fields:
    Optional fields:
        inf_id: 공공데이터ID
        inf_nm: 공공데이터명
        src_exp: 원본시스템
    """

    # Required

    # Optional - only added to query if not empty
    inf_id: str | None = Field(default=None, description="공공데이터ID")
    inf_nm: str | None = Field(default=None, description="공공데이터명")
    src_exp: str | None = Field(default=None, description="원본시스템")

    model_config = ConfigDict(
        populate_by_name=True,
    )

    def to_query_params(self) -> dict[str, Any]:
        """Convert parameters to URL query parameters.
        
        Only non-empty values are included in the query parameters.
        """
        params = super().to_query_params()

        # Required parameter

        # Optional parameters - only add if not None and not empty

        return params

class Response(BaseModel):
    """Response model for OPENSRVAPI endpoint."""
    inf_id: str = Field(alias="INF_ID", description="공공데이터ID")
    inf_nm: str = Field(alias="INF_NM", description="공공데이터명")
    inf_exp: str = Field(alias="INF_EXP", description="공공데이터설명")
    cate_nm: str = Field(alias="CATE_NM", description="분류체계")
    open_dttm: str = Field(alias="OPEN_DTTM", description="공개일자")
    org_nm: str = Field(alias="ORG_NM", description="제공기관")
    load_dttm: str = Field(alias="LOAD_DTTM", description="최종수정일자")
    src_exp: str = Field(alias="SRC_EXP", description="원본시스템")
    ddc_url: str = Field(alias="DDC_URL", description="명세서URL")
    srv_url: str = Field(alias="SRV_URL", description="서비스URL")
    ccl_nm: str = Field(alias="CCL_NM", description="이용허락조건")
    load_nm: str = Field(alias="LOAD_NM", description="공개주기")
    load_cont: str = Field(alias="LOAD_CONT", description="공개시기")
    
    model_config = ConfigDict(
        populate_by_name=True,
        str_strip_whitespace=True,
    )

    @field_validator("*", mode="before")
    @classmethod
    def convert_to_string(cls, v: Any) -> str:
        """Convert all values to string.
        
        API may return numbers or other types instead of strings.
        """
        if v is None:
            return ""
        return str(v)

def fetch(
    client: Client,
    params: Params,
) -> APIResponse[Response]:
    """Fetch OPENSRVAPI data from API.

    Args:
        client: API client instance
        params: Request parameters 

    Returns:
        API response with OPENSRVAPI data
    """
    return client._fetch_api(
        endpoint=ENDPOINT,
        params=params,
        response_model=Response,
    )
