"""VCONFBUDGETCONFLIST endpoint 

ID : OOWY4R001216HX11505
예결산특별위원회 회의록
예결산특별위원회 회의록을 제공합니다.
URL : https://open.assembly.go.kr/portal/data/service/selectAPIServicePage.do/OOWY4R001216HX11505
CCL : 공공누리 - 공공저작물 자유이용허락 : 출처표시

"""

# Code generated by OpenAssembly-Binder. DO NOT EDIT.
# https://github.com/kr-data-kit/KAssembly-CodeGen

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

from models import APIResponse, BaseParams

if TYPE_CHECKING:
    from client import Client

__all__ = [
    "Params",
    "Response",
    "fetch",
    "fetch_bulk",
]

# Endpoint metadata
ENDPOINT = "VCONFBUDGETCONFLIST"
INF_ID = "OOWY4R001216HX11505"
INF_SEQ = "1"


class Params(BaseParams):
    """Request parameters for VCONFBUDGETCONFLIST endpoint.

    This endpoint provides 예결산특별위원회 회의록

    Required fields:
        eraco: 대수
    Optional fields:
        cmit_cd: 위원회코드
    """

    # Required
    eraco: str = Field(..., description="대수")

    # Optional - only added to query if not empty
    cmit_cd: str | None = Field(default=None, description="위원회코드")

    model_config = ConfigDict(
        populate_by_name=True,
    )

    def to_query_params(self) -> dict[str, Any]:
        """Convert parameters to URL query parameters.
        
        Only non-empty values are included in the query parameters.
        """
        params = super().to_query_params()

        # Required parameter
        params["ERACO"] = self.eraco

        # Optional parameters - only add if not None and not empty
        if self.eraco :
            params["ERACO"] = self.eraco

        return params

class Response(BaseModel):
    """Response model for VCONFBUDGETCONFLIST endpoint."""
    conf_id: str = Field(alias="CONF_ID", description="회의ID")
    eraco: str = Field(alias="ERACO", description="대수")
    sess: str = Field(alias="SESS", description="회기")
    dgr: str = Field(alias="DGR", description="차수")
    conf_dt: str = Field(alias="CONF_DT", description="회의일자")
    conf_knd: str = Field(alias="CONF_KND", description="회의종류")
    cmit_cd: str = Field(alias="CMIT_CD", description="위원회코드")
    cmit_nm: str = Field(alias="CMIT_NM", description="위원회명")
    down_url: str = Field(alias="DOWN_URL", description="다운로드 URL")
    
    model_config = ConfigDict(
        populate_by_name=True,
        str_strip_whitespace=True,
    )

    @field_validator("*", mode="before")
    @classmethod
    def convert_to_string(cls, v: Any) -> str:
        """Convert all values to string.
        
        API may return numbers or other types instead of strings.
        """
        if v is None:
            return ""
        return str(v)

def fetch(
    client: Client,
    params: Params,
) -> APIResponse[Response]:
    """Fetch VCONFBUDGETCONFLIST data from API.

    Args:
        client: API client instance
        params: Request parameters 

    Returns:
        API response with VCONFBUDGETCONFLIST data
    """
    return client._fetch_api(
        endpoint=ENDPOINT,
        params=params,
        response_model=Response,
    )
def fetch_bulk(
    client: Client,
    params: Params | None = None,
) -> APIResponse[Response]:
    """Fetch all VCONFBUDGETCONFLIST data via bulk JSON endpoint.

    Note: This method can handle large datasets (10,000+ items) but may
    impose significant load. Use sparingly for very large datasets.

    Args:
        client: API client instance
    
    Returns:
        API response with all VCONFBUDGETCONFLIST data
    """
    param_fields = [
        "ERACO",
        "CMIT_CD",
    ]
    param_values = None
    if params is not None:
        param_values = {
            "ERACO": params.eraco or "",
            "CMIT_CD": params.cmit_cd or "",
        }
    
    return client.fetch_bulk(
        inf_id=INF_ID,
        inf_seq=INF_SEQ,
        param_fields=param_fields,
        param_values=param_values,
        response_model=Response,
    )
