// Code generated by OpenAssembly-Binder. DO NOT EDIT.
// https://github.com/kr-data-kit/KAssembly-CodeGen

package openassemblyclient

import (
	"context"
	"net/url"
)

// ID : OOWY4R001216HX11505
// 예결산특별위원회 회의록
// 예결산특별위원회 회의록을 제공합니다.
// URL : https://open.assembly.go.kr/portal/data/service/selectAPIServicePage.do/OOWY4R001216HX11505
// CCL : 공공누리 - 공공저작물 자유이용허락 : 출처표시

const (
    OOWY4R001216HX11505ApiRes = "VCONFBUDGETCONFLIST"
    OOWY4R001216HX11505InfId = "OOWY4R001216HX11505"
)

// OOWY4R001216HX11505Params is an alias for ID of original VCONFBUDGETCONFLISTParams
type OOWY4R001216HX11505Params = VCONFBUDGETCONFLISTParams

// OOWY4R001216HX11505 is an alias for ID of original VCONFBUDGETCONFLIST
type OOWY4R001216HX11505 = VCONFBUDGETCONFLIST

// VCONFBUDGETCONFLISTParams is a parameter struct for 예결산특별위원회 회의록.
// API : 예결산특별위원회 회의록을 제공합니다.
type VCONFBUDGETCONFLISTParams struct {
    CommonParams
    // Eraco : 대수 [Required] 
    Eraco string `query:"ERACO" db:"eraco"`
    // CmitCd : 위원회코드
    CmitCd string `query:"CMIT_CD" db:"cmit_cd"`
}

func (p *VCONFBUDGETCONFLISTParams) Next()               { p.Index += 1 }
func (p *VCONFBUDGETCONFLISTParams) PageIndex(index int) { p.Index = index }
func (p *VCONFBUDGETCONFLISTParams) PageSize(size int)   { p.Size = size }

// Encode encodes VCONFBUDGETCONFLISTParams as URL query parameters.
func (p *VCONFBUDGETCONFLISTParams) Encode(params *url.Values) {
    p.CommonParams.Encode(params)
    if p.Eraco != "" {
        params.Add("ERACO", p.Eraco)
    }
    if p.CmitCd != "" {
        params.Add("CMIT_CD", p.CmitCd)
    }
}

// VCONFBUDGETCONFLIST is a result struct for 예결산특별위원회 회의록.
// API : 예결산특별위원회 회의록을 제공합니다.
type VCONFBUDGETCONFLIST struct {
    // ConfId : 회의ID
    ConfId string `json:"CONF_ID" db:"conf_id"`
    // Eraco : 대수
    Eraco string `json:"ERACO" db:"eraco"`
    // Sess : 회기
    Sess string `json:"SESS" db:"sess"`
    // Dgr : 차수
    Dgr string `json:"DGR" db:"dgr"`
    // ConfDt : 회의일자
    ConfDt string `json:"CONF_DT" db:"conf_dt"`
    // ConfKnd : 회의종류
    ConfKnd string `json:"CONF_KND" db:"conf_knd"`
    // CmitCd : 위원회코드
    CmitCd string `json:"CMIT_CD" db:"cmit_cd"`
    // CmitNm : 위원회명
    CmitNm string `json:"CMIT_NM" db:"cmit_nm"`
    // DownUrl : 다운로드 URL
    DownUrl string `json:"DOWN_URL" db:"down_url"`
}

// GetConfId returns the "회의ID" value.
func (r *VCONFBUDGETCONFLIST) GetConfId() string {
    return r.ConfId
}

// GetEraco returns the "대수" value.
func (r *VCONFBUDGETCONFLIST) GetEraco() string {
    return r.Eraco
}

// GetSess returns the "회기" value.
func (r *VCONFBUDGETCONFLIST) GetSess() string {
    return r.Sess
}

// GetDgr returns the "차수" value.
func (r *VCONFBUDGETCONFLIST) GetDgr() string {
    return r.Dgr
}

// GetConfDt returns the "회의일자" value.
func (r *VCONFBUDGETCONFLIST) GetConfDt() string {
    return r.ConfDt
}

// GetConfKnd returns the "회의종류" value.
func (r *VCONFBUDGETCONFLIST) GetConfKnd() string {
    return r.ConfKnd
}

// GetCmitCd returns the "위원회코드" value.
func (r *VCONFBUDGETCONFLIST) GetCmitCd() string {
    return r.CmitCd
}

// GetCmitNm returns the "위원회명" value.
func (r *VCONFBUDGETCONFLIST) GetCmitNm() string {
    return r.CmitNm
}

// GetDownUrl returns the "다운로드 URL" value.
func (r *VCONFBUDGETCONFLIST) GetDownUrl() string {
    return r.DownUrl
}

// VCONFBUDGETCONFLISTBuilder is a builder for 예결산특별위원회 회의록.
type VCONFBUDGETCONFLISTBuilder struct {
    BaseAPIRequester[*VCONFBUDGETCONFLISTParams, VCONFBUDGETCONFLIST]
}

// Next increments the page index.
func (b *VCONFBUDGETCONFLISTBuilder) Next() *VCONFBUDGETCONFLISTBuilder {
	b.BaseAPIRequester.Next()
	return b
}

// PageIndex sets the page index.
func (b *VCONFBUDGETCONFLISTBuilder) PageIndex(index int) *VCONFBUDGETCONFLISTBuilder {
	b.BaseAPIRequester.PageIndex(index)
	return b
}

// PageSize sets the page size.
func (b *VCONFBUDGETCONFLISTBuilder) PageSize(size int) *VCONFBUDGETCONFLISTBuilder {
	b.BaseAPIRequester.PageSize(size)
	return b
}

// Eraco sets the 대수 parameter.
func (b *VCONFBUDGETCONFLISTBuilder) Eraco(value string) *VCONFBUDGETCONFLISTBuilder {
    b.params.Eraco = value
    return b
}

// CmitCd sets the 위원회코드 parameter.
func (b *VCONFBUDGETCONFLISTBuilder) CmitCd(value string) *VCONFBUDGETCONFLISTBuilder {
    b.params.CmitCd = value
    return b
}

// Fetch calls the 예결산특별위원회 회의록 API.
func (b *VCONFBUDGETCONFLISTBuilder) Fetch(ctx context.Context) (Response[VCONFBUDGETCONFLIST], error) {
    return b.BaseAPIRequester.Fetch(ctx)
}

// FetchVCONFBUDGETCONFLISTBulkJson fetches data from the 예결산특별위원회 회의록 API using the bulk JSON endpoint.
// Note: While this function can handle datasets of 10,000 items or more, processing such large volumes may impose significant load on the server or runtime.
// Avoid frequent use on very large datasets to prevent performance and stability issues.
func (b *VCONFBUDGETCONFLISTBuilder) FetchBulkJson(ctx context.Context) (Response[VCONFBUDGETCONFLIST], error) {
    return fetchBulkJson[VCONFBUDGETCONFLIST](
        ctx,
        b.client,
        OOWY4R001216HX11505InfId,
        "1",
        *b.params,
    )
}

// NewVCONFBUDGETCONFLISTBuilder creates a new VCONFBUDGETCONFLISTBuilder
func (c *OpenAssemblyClient) NewVCONFBUDGETCONFLISTBuilder() *VCONFBUDGETCONFLISTBuilder {
    return &VCONFBUDGETCONFLISTBuilder{
        BaseAPIRequester: BaseAPIRequester[*VCONFBUDGETCONFLISTParams, VCONFBUDGETCONFLIST]{
            client: c,
            params: &VCONFBUDGETCONFLISTParams{},
            apiResKey: "VCONFBUDGETCONFLIST",
        },
    }
}
