// Code generated by OpenAssembly-Binder. DO NOT EDIT.
// https://github.com/kr-data-kit/KAssembly-CodeGen

package openassemblyclient

import (
	"context"
	"net/url"
)

// ID : OOBAOA001213RL17443
// OPEN API 전체 현황
// OPEN API 전체현황
// URL : https://open.assembly.go.kr/portal/data/service/selectAPIServicePage.do/OOBAOA001213RL17443
// CCL : 공공누리 - 공공저작물 자유이용허락 : 출처표시

const (
    OOBAOA001213RL17443ApiRes = "OPENSRVAPI"
    OOBAOA001213RL17443InfId = "OOBAOA001213RL17443"
)

// OOBAOA001213RL17443Params is an alias for ID of original OPENSRVAPIParams
type OOBAOA001213RL17443Params = OPENSRVAPIParams

// OOBAOA001213RL17443 is an alias for ID of original OPENSRVAPI
type OOBAOA001213RL17443 = OPENSRVAPI

// OPENSRVAPIParams is a parameter struct for OPEN API 전체 현황.
// API : OPEN API 전체현황
type OPENSRVAPIParams struct {
    CommonParams
    // InfId : 공공데이터ID
    InfId string `query:"INF_ID" db:"inf_id"`
    // InfNm : 공공데이터명
    InfNm string `query:"INF_NM" db:"inf_nm"`
    // SrcExp : 원본시스템
    SrcExp string `query:"SRC_EXP" db:"src_exp"`
}

func (p *OPENSRVAPIParams) Next()               { p.Index += 1 }
func (p *OPENSRVAPIParams) PageIndex(index int) { p.Index += index }
func (p *OPENSRVAPIParams) PageSize(size int)   { p.Size += size }

// Encode encodes OPENSRVAPIParams as URL query parameters.
func (p *OPENSRVAPIParams) Encode(params *url.Values) {
    p.CommonParams.Encode(params)
    if p.InfId != "" {
        params.Add("INF_ID", p.InfId)
    }
    if p.InfNm != "" {
        params.Add("INF_NM", p.InfNm)
    }
    if p.SrcExp != "" {
        params.Add("SRC_EXP", p.SrcExp)
    }
}

// OPENSRVAPI is a result struct for OPEN API 전체 현황.
// API : OPEN API 전체현황
type OPENSRVAPI struct {
    // InfId : 공공데이터ID
    InfId string `json:"INF_ID" db:"inf_id"`
    // InfNm : 공공데이터명
    InfNm string `json:"INF_NM" db:"inf_nm"`
    // InfExp : 공공데이터설명
    InfExp string `json:"INF_EXP" db:"inf_exp"`
    // CateNm : 분류체계
    CateNm string `json:"CATE_NM" db:"cate_nm"`
    // OpenDttm : 공개일자
    OpenDttm string `json:"OPEN_DTTM" db:"open_dttm"`
    // OrgNm : 제공기관
    OrgNm string `json:"ORG_NM" db:"org_nm"`
    // LoadDttm : 최종수정일자
    LoadDttm string `json:"LOAD_DTTM" db:"load_dttm"`
    // SrcExp : 원본시스템
    SrcExp string `json:"SRC_EXP" db:"src_exp"`
    // DdcUrl : 명세서URL
    DdcUrl string `json:"DDC_URL" db:"ddc_url"`
    // SrvUrl : 서비스URL
    SrvUrl string `json:"SRV_URL" db:"srv_url"`
    // CclNm : 이용허락조건
    CclNm string `json:"CCL_NM" db:"ccl_nm"`
    // LoadNm : 공개주기
    LoadNm string `json:"LOAD_NM" db:"load_nm"`
    // LoadCont : 공개시기
    LoadCont string `json:"LOAD_CONT" db:"load_cont"`
}

// GetInfId returns the "공공데이터ID" value.
func (r *OPENSRVAPI) GetInfId() string {
    return r.InfId
}

// GetInfNm returns the "공공데이터명" value.
func (r *OPENSRVAPI) GetInfNm() string {
    return r.InfNm
}

// GetInfExp returns the "공공데이터설명" value.
func (r *OPENSRVAPI) GetInfExp() string {
    return r.InfExp
}

// GetCateNm returns the "분류체계" value.
func (r *OPENSRVAPI) GetCateNm() string {
    return r.CateNm
}

// GetOpenDttm returns the "공개일자" value.
func (r *OPENSRVAPI) GetOpenDttm() string {
    return r.OpenDttm
}

// GetOrgNm returns the "제공기관" value.
func (r *OPENSRVAPI) GetOrgNm() string {
    return r.OrgNm
}

// GetLoadDttm returns the "최종수정일자" value.
func (r *OPENSRVAPI) GetLoadDttm() string {
    return r.LoadDttm
}

// GetSrcExp returns the "원본시스템" value.
func (r *OPENSRVAPI) GetSrcExp() string {
    return r.SrcExp
}

// GetDdcUrl returns the "명세서URL" value.
func (r *OPENSRVAPI) GetDdcUrl() string {
    return r.DdcUrl
}

// GetSrvUrl returns the "서비스URL" value.
func (r *OPENSRVAPI) GetSrvUrl() string {
    return r.SrvUrl
}

// GetCclNm returns the "이용허락조건" value.
func (r *OPENSRVAPI) GetCclNm() string {
    return r.CclNm
}

// GetLoadNm returns the "공개주기" value.
func (r *OPENSRVAPI) GetLoadNm() string {
    return r.LoadNm
}

// GetLoadCont returns the "공개시기" value.
func (r *OPENSRVAPI) GetLoadCont() string {
    return r.LoadCont
}

// OPENSRVAPIBuilder is a builder for OPEN API 전체 현황.
type OPENSRVAPIBuilder struct {
    BaseAPIRequester[*OPENSRVAPIParams, OPENSRVAPI]
}

// Next increments the page index.
func (b *OPENSRVAPIBuilder) Next() *OPENSRVAPIBuilder {
	b.BaseAPIRequester.Next()
	return b
}

// PageIndex sets the page index.
func (b *OPENSRVAPIBuilder) PageIndex(index int) *OPENSRVAPIBuilder {
	b.BaseAPIRequester.PageIndex(index)
	return b
}

// PageSize sets the page size.
func (b *OPENSRVAPIBuilder) PageSize(size int) *OPENSRVAPIBuilder {
	b.BaseAPIRequester.PageSize(size)
	return b
}

// InfId sets the 공공데이터ID parameter.
func (b *OPENSRVAPIBuilder) InfId(value string) *OPENSRVAPIBuilder {
    b.params.InfId = value
    return b
}

// InfNm sets the 공공데이터명 parameter.
func (b *OPENSRVAPIBuilder) InfNm(value string) *OPENSRVAPIBuilder {
    b.params.InfNm = value
    return b
}

// SrcExp sets the 원본시스템 parameter.
func (b *OPENSRVAPIBuilder) SrcExp(value string) *OPENSRVAPIBuilder {
    b.params.SrcExp = value
    return b
}

// Fetch calls the OPEN API 전체 현황 API.
func (b *OPENSRVAPIBuilder) Fetch(ctx context.Context) (Response[OPENSRVAPI], error) {
    return b.BaseAPIRequester.Fetch(ctx)
}

// FetchOPENSRVAPIBulkJson fetches data from the OPEN API 전체 현황 API using bulk JSON endpoint.
// BindTemplate renders the bind template to produce assembly binding code.
// It consumes input data describing components and relationships and outputs the generated code.
// Note: While this function can handle datasets of 10,000 items or more, processing such large volumes may impose significant load on the server or runtime.
// Avoid frequent use on very large datasets to prevent performance and stability issues.
func (b *OPENSRVAPIBuilder) FetchBulkJson(ctx context.Context) (Response[OPENSRVAPI], error) {
    return b.BaseAPIRequester.Fetch(ctx)
}

// NewOPENSRVAPIBuilder creates a new OPENSRVAPIBuilder
func (c *OpenAssemblyClient) NewOPENSRVAPIBuilder() *OPENSRVAPIBuilder {
    return &OPENSRVAPIBuilder{
        BaseAPIRequester: BaseAPIRequester[*OPENSRVAPIParams, OPENSRVAPI]{
            client: c,
            params: &OPENSRVAPIParams{},
            apiResKey: "OPENSRVAPI",
        },
    }
}
