// Code generated by OpenAssembly-Binder. DO NOT EDIT.
// https://github.com/kr-data-kit/KAssembly-CodeGen

package openassemblyclient

import (
	"context"
	"net/url"
)

// ID : OOBAOA001213RL17443
// OPEN API 전체 현황
// OPEN API 전체현황
// URL : https://open.assembly.go.kr/portal/data/service/selectAPIServicePage.do/OOBAOA001213RL17443
// CCL : 공공누리 - 공공저작물 자유이용허락 : 출처표시

const (
    OOBAOA001213RL17443ApiRes = "OPENSRVAPI"
    OOBAOA001213RL17443InfId = "OOBAOA001213RL17443"
)

// OOBAOA001213RL17443Params is an alias for ID of original OPENSRVAPIParams
type OOBAOA001213RL17443Params = OPENSRVAPIParams

// OOBAOA001213RL17443 is an alias for ID of original OPENSRVAPI
type OOBAOA001213RL17443 = OPENSRVAPI

// OPENSRVAPIParams is a parameter struct for OPEN API 전체 현황.
// API : OPEN API 전체현황
type OPENSRVAPIParams struct {
    CommonParams
    // InfId : 공공데이터ID
    InfId string `query:"INF_ID" db:"inf_id"`
    // InfNm : 공공데이터명
    InfNm string `query:"INF_NM" db:"inf_nm"`
    // SrcExp : 원본시스템
    SrcExp string `query:"SRC_EXP" db:"src_exp"`
}

// OPENSRVAPI is a result struct for OPEN API 전체 현황.
// API : OPEN API 전체현황
type OPENSRVAPI struct {
    // InfId : 공공데이터ID
    InfId string `json:"INF_ID" db:"inf_id"`
    // InfNm : 공공데이터명
    InfNm string `json:"INF_NM" db:"inf_nm"`
    // InfExp : 공공데이터설명
    InfExp string `json:"INF_EXP" db:"inf_exp"`
    // CateNm : 분류체계
    CateNm string `json:"CATE_NM" db:"cate_nm"`
    // OpenDttm : 공개일자
    OpenDttm string `json:"OPEN_DTTM" db:"open_dttm"`
    // OrgNm : 제공기관
    OrgNm string `json:"ORG_NM" db:"org_nm"`
    // LoadDttm : 최종수정일자
    LoadDttm string `json:"LOAD_DTTM" db:"load_dttm"`
    // SrcExp : 원본시스템
    SrcExp string `json:"SRC_EXP" db:"src_exp"`
    // DdcUrl : 명세서URL
    DdcUrl string `json:"DDC_URL" db:"ddc_url"`
    // SrvUrl : 서비스URL
    SrvUrl string `json:"SRV_URL" db:"srv_url"`
    // CclNm : 이용허락조건
    CclNm string `json:"CCL_NM" db:"ccl_nm"`
    // LoadNm : 공개주기
    LoadNm string `json:"LOAD_NM" db:"load_nm"`
    // LoadCont : 공개시기
    LoadCont string `json:"LOAD_CONT" db:"load_cont"`
}

// Encode encodes OPENSRVAPIParams as URL query parameters.
func (p *OPENSRVAPIParams) Encode(params *url.Values) {
    p.CommonParams.Encode(params)
    if p.InfId != "" {
        params.Add("INF_ID", p.InfId)
    }
    if p.InfNm != "" {
        params.Add("INF_NM", p.InfNm)
    }
    if p.SrcExp != "" {
        params.Add("SRC_EXP", p.SrcExp)
    }
}

// FetchOPENSRVAPI calls the OPEN API 전체 현황 API.
func (c *OpenAssemblyClient) FetchOPENSRVAPI(
    ctx context.Context,
    params *OPENSRVAPIParams,
) (Response[OPENSRVAPI], error) {
    return fetchApi[OPENSRVAPI](ctx, c, "OPENSRVAPI", params)
}

// IsValid checks the validity of OPENSRVAPIParams.
func (p *OPENSRVAPIParams) IsValid() bool {
    return true
}

