// Code generated by OpenAssembly-Binder. DO NOT EDIT.
// https://github.com/kr-data-kit/KAssembly-CodeGen

package openassemblyclient

import (
	"context"
	"net/url"
)

// ID : OOWY4R001216HX11440
// 의안정보 통합 API (Version 1)
// 의안정보 통합 API의 정보를 제공합니다. - Updated Version
// URL : https://open.assembly.go.kr/portal/data/service/selectAPIServicePage.do/OOWY4R001216HX11440
// CCL : 공공누리 - 공공저작물 자유이용허락 : 출처표시

const (
    OOWY4R001216HX11440ApiRes = "ALLBILL"
    OOWY4R001216HX11440InfId = "OOWY4R001216HX11440"
)

// OOWY4R001216HX11440Params is an alias for ID of original ALLBILLParams
type OOWY4R001216HX11440Params = ALLBILLParams

// OOWY4R001216HX11440 is an alias for ID of original ALLBILL
type OOWY4R001216HX11440 = ALLBILL

// ALLBILLParams is a parameter struct for 의안정보 통합 API (Version 1).
// API : 의안정보 통합 API의 정보를 제공합니다. - Updated Version
type ALLBILLParams struct {
    CommonParams
    // BillId : 의안ID
    // (Reference : BILL_ID='PRC_L2J3K0I5Q1R1P0P9O4P2N1N6V1W8U9')
    BillId string `query:"BILL_ID" db:"bill_id"`
    // BillNo : 의안번호 [Required] 
    // (Reference : BILL_NO='2123836')
    BillNo string `query:"BILL_NO" db:"bill_no"`
    // BillKnd : 의안종류
    // (Reference : BILL_KND='의안종류 검색어'  (예시) BILL_KND=법률안)
    BillKnd string `query:"BILL_KND" db:"bill_knd"`
    // BillNm : 의안명
    // (Reference : BILL_NM='의안명 검색어'  (예시) BILL_NM=환경친화)
    BillNm string `query:"BILL_NM" db:"bill_nm"`
    // PpsrKnd : 제안자구분
    // (Reference : PPSR_KND='제안자구분 검색어'  (예시) PPSR_KND=의원)
    PpsrKnd string `query:"PPSR_KND" db:"ppsr_knd"`
    // PpslDt : 제안일
    // (Reference : PPSL_DT='제안일 검색어'  (예시) PPSL_DT=2023)
    PpslDt string `query:"PPSL_DT" db:"ppsl_dt"`
    // JrcmitNm : 소관위원회명
    // (Reference : JRCMIT_NM='소관위원회명 검색어'  (예시) JRCMIT_NM=교육위원)
    JrcmitNm string `query:"JRCMIT_NM" db:"jrcmit_nm"`
    // RgsConfRslt : 본회의 심의결과
    // (Reference : RGS_CONF_RSLT='본회의 심의결과 검색어'  (예시) RGS_CONF_RSLT=원안가결)
    RgsConfRslt string `query:"RGS_CONF_RSLT" db:"rgs_conf_rslt"`
}

func (p *ALLBILLParams) Next()               { p.Index += 1 }
func (p *ALLBILLParams) PageIndex(index int) { p.Index = index }
func (p *ALLBILLParams) PageSize(size int)   { p.Size = size }

// Encode encodes ALLBILLParams as URL query parameters.
func (p *ALLBILLParams) Encode(params *url.Values) {
    p.CommonParams.Encode(params)
    if p.BillId != "" {
        params.Add("BILL_ID", p.BillId)
    }
    if p.BillNo != "" {
        params.Add("BILL_NO", p.BillNo)
    }
    if p.BillKnd != "" {
        params.Add("BILL_KND", p.BillKnd)
    }
    if p.BillNm != "" {
        params.Add("BILL_NM", p.BillNm)
    }
    if p.PpsrKnd != "" {
        params.Add("PPSR_KND", p.PpsrKnd)
    }
    if p.PpslDt != "" {
        params.Add("PPSL_DT", p.PpslDt)
    }
    if p.JrcmitNm != "" {
        params.Add("JRCMIT_NM", p.JrcmitNm)
    }
    if p.RgsConfRslt != "" {
        params.Add("RGS_CONF_RSLT", p.RgsConfRslt)
    }
}

// ALLBILL is a result struct for 의안정보 통합 API (Version 1).
// API : 의안정보 통합 API의 정보를 제공합니다. - Updated Version
type ALLBILL struct {
    // Eraco : 대수
    Eraco string `json:"ERACO" db:"eraco"`
    // BillId : 의안ID
    BillId string `json:"BILL_ID" db:"bill_id"`
    // BillNo : 의안번호
    BillNo string `json:"BILL_NO" db:"bill_no"`
    // BillKnd : 의안종류
    BillKnd string `json:"BILL_KND" db:"bill_knd"`
    // BillNm : 의안명
    BillNm string `json:"BILL_NM" db:"bill_nm"`
    // PpsrKnd : 제안자구분
    PpsrKnd string `json:"PPSR_KND" db:"ppsr_knd"`
    // PpsrNm : 제안자명
    PpsrNm string `json:"PPSR_NM" db:"ppsr_nm"`
    // PpslSess : 제안회기
    PpslSess string `json:"PPSL_SESS" db:"ppsl_sess"`
    // PpslDt : 제안일
    PpslDt string `json:"PPSL_DT" db:"ppsl_dt"`
    // JrcmitNm : 소관위원회명
    JrcmitNm string `json:"JRCMIT_NM" db:"jrcmit_nm"`
    // JrcmitCmmtDt : 소관위원회 회부일
    JrcmitCmmtDt string `json:"JRCMIT_CMMT_DT" db:"jrcmit_cmmt_dt"`
    // JrcmitPrsntDt : 소관위원회 상정일
    JrcmitPrsntDt string `json:"JRCMIT_PRSNT_DT" db:"jrcmit_prsnt_dt"`
    // JrcmitProcDt : 소관위원회 처리일
    JrcmitProcDt string `json:"JRCMIT_PROC_DT" db:"jrcmit_proc_dt"`
    // JrcmitProcRslt : 소관위원회 처리결과
    JrcmitProcRslt string `json:"JRCMIT_PROC_RSLT" db:"jrcmit_proc_rslt"`
    // LawCmmtDt : 법사위 체계자구심사 회부일
    LawCmmtDt string `json:"LAW_CMMT_DT" db:"law_cmmt_dt"`
    // LawPrsntDt : 법사위 체계자구심사 상정일
    LawPrsntDt string `json:"LAW_PRSNT_DT" db:"law_prsnt_dt"`
    // LawProcDt : 법사위 체계자구심사 처리일
    LawProcDt string `json:"LAW_PROC_DT" db:"law_proc_dt"`
    // LawProcRslt : 법사위 체계자구심사 처리결과
    LawProcRslt string `json:"LAW_PROC_RSLT" db:"law_proc_rslt"`
    // RgsPrsntDt : 본회의 심의 상정일
    RgsPrsntDt string `json:"RGS_PRSNT_DT" db:"rgs_prsnt_dt"`
    // RgsRslnDt : 본회의 심의 의결일
    RgsRslnDt string `json:"RGS_RSLN_DT" db:"rgs_rsln_dt"`
    // RgsConfNm : 본회의 심의 회의명
    RgsConfNm string `json:"RGS_CONF_NM" db:"rgs_conf_nm"`
    // RgsConfRslt : 본회의 심의결과
    RgsConfRslt string `json:"RGS_CONF_RSLT" db:"rgs_conf_rslt"`
    // GvrnTrsfDt : 정부 이송일
    GvrnTrsfDt string `json:"GVRN_TRSF_DT" db:"gvrn_trsf_dt"`
    // PromLawNm : 공포 법률명
    PromLawNm string `json:"PROM_LAW_NM" db:"prom_law_nm"`
    // PromDt : 공포일
    PromDt string `json:"PROM_DT" db:"prom_dt"`
    // PromNo : 공포번호
    PromNo string `json:"PROM_NO" db:"prom_no"`
    // LinkUrl : 링크URL
    LinkUrl string `json:"LINK_URL" db:"link_url"`
}

// GetEraco returns the "대수" value.
func (r *ALLBILL) GetEraco() string {
    return r.Eraco
}

// GetBillId returns the "의안ID" value.
func (r *ALLBILL) GetBillId() string {
    return r.BillId
}

// GetBillNo returns the "의안번호" value.
func (r *ALLBILL) GetBillNo() string {
    return r.BillNo
}

// GetBillKnd returns the "의안종류" value.
func (r *ALLBILL) GetBillKnd() string {
    return r.BillKnd
}

// GetBillNm returns the "의안명" value.
func (r *ALLBILL) GetBillNm() string {
    return r.BillNm
}

// GetPpsrKnd returns the "제안자구분" value.
func (r *ALLBILL) GetPpsrKnd() string {
    return r.PpsrKnd
}

// GetPpsrNm returns the "제안자명" value.
func (r *ALLBILL) GetPpsrNm() string {
    return r.PpsrNm
}

// GetPpslSess returns the "제안회기" value.
func (r *ALLBILL) GetPpslSess() string {
    return r.PpslSess
}

// GetPpslDt returns the "제안일" value.
func (r *ALLBILL) GetPpslDt() string {
    return r.PpslDt
}

// GetJrcmitNm returns the "소관위원회명" value.
func (r *ALLBILL) GetJrcmitNm() string {
    return r.JrcmitNm
}

// GetJrcmitCmmtDt returns the "소관위원회 회부일" value.
func (r *ALLBILL) GetJrcmitCmmtDt() string {
    return r.JrcmitCmmtDt
}

// GetJrcmitPrsntDt returns the "소관위원회 상정일" value.
func (r *ALLBILL) GetJrcmitPrsntDt() string {
    return r.JrcmitPrsntDt
}

// GetJrcmitProcDt returns the "소관위원회 처리일" value.
func (r *ALLBILL) GetJrcmitProcDt() string {
    return r.JrcmitProcDt
}

// GetJrcmitProcRslt returns the "소관위원회 처리결과" value.
func (r *ALLBILL) GetJrcmitProcRslt() string {
    return r.JrcmitProcRslt
}

// GetLawCmmtDt returns the "법사위 체계자구심사 회부일" value.
func (r *ALLBILL) GetLawCmmtDt() string {
    return r.LawCmmtDt
}

// GetLawPrsntDt returns the "법사위 체계자구심사 상정일" value.
func (r *ALLBILL) GetLawPrsntDt() string {
    return r.LawPrsntDt
}

// GetLawProcDt returns the "법사위 체계자구심사 처리일" value.
func (r *ALLBILL) GetLawProcDt() string {
    return r.LawProcDt
}

// GetLawProcRslt returns the "법사위 체계자구심사 처리결과" value.
func (r *ALLBILL) GetLawProcRslt() string {
    return r.LawProcRslt
}

// GetRgsPrsntDt returns the "본회의 심의 상정일" value.
func (r *ALLBILL) GetRgsPrsntDt() string {
    return r.RgsPrsntDt
}

// GetRgsRslnDt returns the "본회의 심의 의결일" value.
func (r *ALLBILL) GetRgsRslnDt() string {
    return r.RgsRslnDt
}

// GetRgsConfNm returns the "본회의 심의 회의명" value.
func (r *ALLBILL) GetRgsConfNm() string {
    return r.RgsConfNm
}

// GetRgsConfRslt returns the "본회의 심의결과" value.
func (r *ALLBILL) GetRgsConfRslt() string {
    return r.RgsConfRslt
}

// GetGvrnTrsfDt returns the "정부 이송일" value.
func (r *ALLBILL) GetGvrnTrsfDt() string {
    return r.GvrnTrsfDt
}

// GetPromLawNm returns the "공포 법률명" value.
func (r *ALLBILL) GetPromLawNm() string {
    return r.PromLawNm
}

// GetPromDt returns the "공포일" value.
func (r *ALLBILL) GetPromDt() string {
    return r.PromDt
}

// GetPromNo returns the "공포번호" value.
func (r *ALLBILL) GetPromNo() string {
    return r.PromNo
}

// GetLinkUrl returns the "링크URL" value.
func (r *ALLBILL) GetLinkUrl() string {
    return r.LinkUrl
}

// ALLBILLBuilder is a builder for 의안정보 통합 API (Version 1).
type ALLBILLBuilder struct {
    BaseAPIRequester[*ALLBILLParams, ALLBILL]
}

// Next increments the page index.
func (b *ALLBILLBuilder) Next() *ALLBILLBuilder {
	b.BaseAPIRequester.Next()
	return b
}

// PageIndex sets the page index.
func (b *ALLBILLBuilder) PageIndex(index int) *ALLBILLBuilder {
	b.BaseAPIRequester.PageIndex(index)
	return b
}

// PageSize sets the page size.
func (b *ALLBILLBuilder) PageSize(size int) *ALLBILLBuilder {
	b.BaseAPIRequester.PageSize(size)
	return b
}

// BillId sets the 의안ID parameter.
func (b *ALLBILLBuilder) BillId(value string) *ALLBILLBuilder {
    b.params.BillId = value
    return b
}

// BillNo sets the 의안번호 parameter.
func (b *ALLBILLBuilder) BillNo(value string) *ALLBILLBuilder {
    b.params.BillNo = value
    return b
}

// BillKnd sets the 의안종류 parameter.
func (b *ALLBILLBuilder) BillKnd(value string) *ALLBILLBuilder {
    b.params.BillKnd = value
    return b
}

// BillNm sets the 의안명 parameter.
func (b *ALLBILLBuilder) BillNm(value string) *ALLBILLBuilder {
    b.params.BillNm = value
    return b
}

// PpsrKnd sets the 제안자구분 parameter.
func (b *ALLBILLBuilder) PpsrKnd(value string) *ALLBILLBuilder {
    b.params.PpsrKnd = value
    return b
}

// PpslDt sets the 제안일 parameter.
func (b *ALLBILLBuilder) PpslDt(value string) *ALLBILLBuilder {
    b.params.PpslDt = value
    return b
}

// JrcmitNm sets the 소관위원회명 parameter.
func (b *ALLBILLBuilder) JrcmitNm(value string) *ALLBILLBuilder {
    b.params.JrcmitNm = value
    return b
}

// RgsConfRslt sets the 본회의 심의결과 parameter.
func (b *ALLBILLBuilder) RgsConfRslt(value string) *ALLBILLBuilder {
    b.params.RgsConfRslt = value
    return b
}

// Fetch calls the 의안정보 통합 API (Version 1) API.
func (b *ALLBILLBuilder) Fetch(ctx context.Context) (Response[ALLBILL], error) {
    return b.BaseAPIRequester.Fetch(ctx)
}

// FetchALLBILLBulkJson fetches data from the 의안정보 통합 API (Version 1) API using the bulk JSON endpoint.
// Note: While this function can handle datasets of 10,000 items or more, processing such large volumes may impose significant load on the server or runtime.
// Avoid frequent use on very large datasets to prevent performance and stability issues.
func (b *ALLBILLBuilder) FetchBulkJson(ctx context.Context) (Response[ALLBILL], error) {
    return fetchBulkJson[ALLBILL](
        ctx,
        b.client,
        OOWY4R001216HX11440InfId,
        "1",
        *b.params,
    )
}

// NewALLBILLBuilder creates a new ALLBILLBuilder
func (c *Client) NewALLBILLBuilder() *ALLBILLBuilder {
    return &ALLBILLBuilder{
        BaseAPIRequester: BaseAPIRequester[*ALLBILLParams, ALLBILL]{
            client: c,
            params: &ALLBILLParams{},
            apiResKey: "ALLBILL",
        },
    }
}
