// Code generated by OpenAssembly-Binder. DO NOT EDIT.
// https://github.com/kr-data-kit/KAssembly-CodeGen

package openassemblyclient

import (
	"context"
	"net/url"
)

// ID : OOWY4R001216HX11505
// 예결산특별위원회 회의록
// 예결산특별위원회 회의록을 제공합니다.
// URL : https://open.assembly.go.kr/portal/data/service/selectAPIServicePage.do/OOWY4R001216HX11505
// CCL : 공공누리 - 공공저작물 자유이용허락 : 출처표시

const (
    OOWY4R001216HX11505ApiRes = "VCONFBUDGETCONFLIST"
    OOWY4R001216HX11505InfId = "OOWY4R001216HX11505"
)

// OOWY4R001216HX11505Params is an alias for ID of original VCONFBUDGETCONFLISTParams
type OOWY4R001216HX11505Params = VCONFBUDGETCONFLISTParams

// OOWY4R001216HX11505 is an alias for ID of original VCONFBUDGETCONFLIST
type OOWY4R001216HX11505 = VCONFBUDGETCONFLIST

// VCONFBUDGETCONFLISTParams is a parameter struct for 예결산특별위원회 회의록.
// API : 예결산특별위원회 회의록을 제공합니다.
type VCONFBUDGETCONFLISTParams struct {
    CommonParams
    // Eraco : 대수 [Required] 
    Eraco string `query:"ERACO" db:"eraco"`
    // CmitCd : 위원회코드
    CmitCd string `query:"CMIT_CD" db:"cmit_cd"`
}

// VCONFBUDGETCONFLIST is a result struct for 예결산특별위원회 회의록.
// API : 예결산특별위원회 회의록을 제공합니다.
type VCONFBUDGETCONFLIST struct {
    // ConfId : 회의ID
    ConfId string `json:"CONF_ID" db:"conf_id"`
    // Eraco : 대수
    Eraco string `json:"ERACO" db:"eraco"`
    // Sess : 회기
    Sess string `json:"SESS" db:"sess"`
    // Dgr : 차수
    Dgr string `json:"DGR" db:"dgr"`
    // ConfDt : 회의일자
    ConfDt string `json:"CONF_DT" db:"conf_dt"`
    // ConfKnd : 회의종류
    ConfKnd string `json:"CONF_KND" db:"conf_knd"`
    // CmitCd : 위원회코드
    CmitCd string `json:"CMIT_CD" db:"cmit_cd"`
    // CmitNm : 위원회명
    CmitNm string `json:"CMIT_NM" db:"cmit_nm"`
    // DownUrl : 다운로드 URL
    DownUrl string `json:"DOWN_URL" db:"down_url"`
}

// Encode encodes VCONFBUDGETCONFLISTParams as URL query parameters.
func (p *VCONFBUDGETCONFLISTParams) Encode(params *url.Values) {
    p.CommonParams.Encode(params)
    if p.Eraco != "" {
        params.Add("ERACO", p.Eraco)
    }
    if p.CmitCd != "" {
        params.Add("CMIT_CD", p.CmitCd)
    }
}

// FetchVCONFBUDGETCONFLIST calls the 예결산특별위원회 회의록 API.
func (c *OpenAssemblyClient) FetchVCONFBUDGETCONFLIST(
    ctx context.Context,
    params *VCONFBUDGETCONFLISTParams,
) (Response[VCONFBUDGETCONFLIST], error) {
    return fetchApi[VCONFBUDGETCONFLIST](ctx, c, "VCONFBUDGETCONFLIST", params)
}

// IsValid checks the validity of VCONFBUDGETCONFLISTParams.
func (p *VCONFBUDGETCONFLISTParams) IsValid() bool {
    if p.Eraco == "" {
        return false
    }
    return true
}

// FetchVCONFBUDGETCONFLISTBulkJson fetches data from the 예결산특별위원회 회의록 API using bulk JSON endpoint.
// BindTemplate renders the bind template to produce assembly binding code.
// It consumes input data describing components and relationships and outputs the generated code.
// Note: While this function can handle datasets of 10,000 items or more, processing such large volumes may impose significant load on the server or runtime.
// Avoid frequent use on very large datasets to prevent performance and stability issues.
func (c *OpenAssemblyClient) FetchVCONFBUDGETCONFLISTBulkJson(
    ctx context.Context,
) (Response[VCONFBUDGETCONFLIST], error) {
    return fetchBulkJson[VCONFBUDGETCONFLIST](
        ctx,
        c,
        OOWY4R001216HX11505InfId,
        "1",
        VCONFBUDGETCONFLISTParams{},
    )
}
