// Code generated by OpenAssembly-Binder. DO NOT EDIT.
// https://github.com/kr-data-kit/KAssembly-CodeGen

package openassemblyclient

type HeadItem struct {
	ListTotalCount *int    `json:"list_total_count,omitempty"`
	Result         *Result `json:"RESULT,omitempty"`
}

type Result struct {
	Code    string `json:"CODE"`
	Message string `json:"MESSAGE"`
}

type Item[T any] struct {
	Head []HeadItem `json:"head,omitempty"`
	Row  []T        `json:"row,omitempty"`
}
