// Code generated by OpenAssembly-Binder. DO NOT EDIT.
// https://github.com/kr-data-kit/KAssembly-CodeGen

package openassemblyclient

import (
	"net/url"
	"strconv"
)

type Paging struct {
	Index int `query:"pIndex,omitempty"`
	Size  int `query:"pSize,omitempty"`
}

type CommonParams struct {
	Paging
}

func (c *CommonParams) Encode(params *url.Values) {
	if c.Index != 0 {
		params.Add("pIndex", strconv.Itoa(c.Index))
	}
	if c.Size != 0 {
		params.Add("pSize", strconv.Itoa(c.Size))
	}
}
